# Generated by Django 2.2 on 2021-07-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_auto_20210702_1946'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
    ]
