# Generated by Django 2.2 on 2021-07-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_auto_20210702_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quizz',
        ),
        migrations.AddField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Quiz.Quizz'),
            preserve_default=False,
        ),
    ]
