# Generated by Django 2.2 on 2021-07-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_auto_20210702_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fizyka',
        ),
        migrations.DeleteModel(
            name='Historia',
        ),
        migrations.DeleteModel(
            name='Informatyka',
        ),
        migrations.DeleteModel(
            name='Matematyka',
        ),
    ]
